<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'For {valueName} allowed max size is {maxSize}' => 'Для параметра {valueName} максимальный размер равен {maxSize}',
    'For {valueName} allowed min size is {minSize}' => 'Для параметра {valueName} допустимый минимальный размер {minSize}',
    '{className}: Invalid syntax in {valueName} tag @inArray{restrictions}' => '{className}: недопустимый синтаксис в теге {valueName} @inArray{restrictions}',
    '{valueName} is required and cannot be Null.' => '{valueName} является обязательным и не может быть пустым.',
    '@Null for {valueName} is deprecated. All values can be NULL by default. Please use @NotNull for required properties.' => '@Null для {valueName} устарело. По умолчанию все значения могут быть NULL. Для требуемых свойств используйте @NotNull.',
    'In {className} class \'{type}\' MUST be instance of \'\\JsonRpc2\\Dto\'' => 'В классе {className} класс \'{type} \' ДОЛЖЕН быть экземпляром \'\\JsonRpc2\\Dto\'',
    'In {className} type \'{type}\' is invalid' => 'В {className} тип \'{type}\' недействителен',
    'In {className} value has type \'{type}\', but array expected' => 'В {className} значение имеет тип \'{type}\', но ожидается массив',
    'Internal error' => 'Внутренняя ошибка',
    'Invalid Request' => 'Неверный запрос',
    'Invalid data received for parameter "{param}".' => 'Получены недопустимые данные для параметра "{param}".',
    'Method not found' => 'Метод не найден',
    'Missing required parameters: {params}' => 'Отсутствуют обязательные параметры: {params}',
    'Parameter type \'array\' is deprecated. Use square brackets with simply types or DTO based classes instead.' => 'Тип параметра \'array\' устарел. Вместо этого используйте квадратные скобки с простыми типами или классами DTO.',
    'Parse error' => 'Ошибка синтаксического анализа',
    'Value \'{valueData}\' is not allowed for {valueName}. Allowed values is \'{restrictions}\'' => 'Значение \'{valueData}\' недопустимо для {valueName}. Допустимые значения - \'{restrictions}\'',
    'Value has type \'{type}\', but array expected' => 'Значение имеет тип \'{type}\', но ожидается массив',
];
